[package]
name = "very-simple-image-loader"
version = "0.1.0"
authors = ["chatondecarte"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.5"
minifb = "0.15.3"